# Generated by Django 6.0.5 on 2026-05-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('order', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('menu_type', models.CharField(choices=[('VIP', 'VIP'), ('ECO', 'ECO')], max_length=16)),
                ('price', models.PositiveIntegerField()),
                ('order_in_category', models.SmallIntegerField()),
                ('show_in_menu', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
    ]
